SSEG	SEGMENT	STACK
STK 	DB	50 DUP(0)
SSEG 	ENDS
DSEG	SEGMENT
DATA	DW	1431H,-1236H,-427H,-817H,0359H,1987H,-22H,5087H,1101H
COUNT	DW	09
ASCI 	DB	50 DUP(0)
DSEG	ENDS
CSEG	SEGMENT
		ASSUME	CS:CSEG,DS:DSEG
		ASSUME	SS:SSEG

HTOA	PROC	NEAR		;将一位十六进制数转化为ASCII码
		AND	AL,0FH
		CMP	AL,10
		JC	HTOA1
		ADD	AL,07
HTOA1:	ADD	AL,30H
		RET
HTOA    ENDP

BHTOA	PROC	NEAR        ;将两位十六进制数转化为ASCII码
		PUSH	CX
		MOV	CH,	AL
		MOV	CL,04
		SHR	AL,CL
		CALL	HTOA
		MOV	AH,AL
		MOV	AL,CH
		CALL	HTOA
		POP	CX
		RET
BHTOA	ENDP

QHTOA	PROC	NEAR		;将四位十六进制数转化为ASCII码
		PUSH	AX
		MOV	AL,AH
		CALL	BHTOA
		MOV	BX,AX
		POP	AX
		CALL	BHTOA
		RET
QHTOA	ENDP

OUTPUT_ONE	PROC	NEAR
			MOV	DL,BYTE PTR [DI]
			MOV	AH,02H
			INT 21
			RET
OUTPUT_ONE	ENDP

START:	
		MOV AX,DSEG
		MOV	DS,AX
		MOV CX,WORD PTR COUNT		;外层倒计数循环
AGAIN1:	MOV BX,CX       			;内层循环次数
		LEA SI,DATA	
AGAIN2:	CMP	BX,1					;内层循环结束条件
		JE	NEXT2
		DEC	BX
		MOV	AX,WORD PTR [SI]
		CMP AX,[SI+2]
		JG	SWAP
		ADD	SI,2
		JMP	AGAIN2
SWAP:	XCHG AX,WORD PTR [SI+2]
		XCHG AX,WORD PTR [SI]	
		ADD SI,2
		JMP	AGAIN2			
NEXT2: 	LOOP AGAIN1	       			;以上为冒泡排序部分

		LEA	SI,DATA
		LEA	DI,ASCI
		MOV	CX,COUNT
AGAIN:	MOV	AX,[SI]					;将要转化的四位十六进制数放到AX里
		CALL	QHTOA
		MOV	[DI],BH
		MOV	[DI+1],BL
		MOV [DI+2],AH
		MOV	[DI+3],AL
		MOV	BYTE PTR[DI+4],','
		ADD	DI,5
		ADD	SI,2
		LOOP	AGAIN

		LEA	DI,ASCI
		MOV	AX,WORD	PTR	COUNT
		MOV	CX,4
		MUL	CX
		MOV	CX,AX					;计算出输出时的循环次数
OUTPUT:	
		CALL	OUTPUT_ONE
		INC DI
		LOOP	OUTPUT

		MOV AH,4CH
		INT 21H

CSEG	ENDS
		END 	START
